language: node_js
node_js:
  - '12.13'
before_install:
  - npm install -g typescript

script:
  - npm run build
  - npm run test

deploy:
  cleanup: false
  provider: npm
  email: eoind@vey.ie
  on:
    tags: true
    repo: EoinDavey/tsPEG
  api_key: "$NPM_TOKEN"
  edge: true
